"use strict";
  const Audio={ctx:null,master:null,muted:false,vol:0.5,lastShot:0,lastCog:0,lastExplo:0,
    init(){if(this.ctx)return;try{this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=this.muted?0:this.vol;this.master.connect(this.ctx.destination);}catch(e){}},
    resume(){try{if(this.ctx&&this.ctx.state==='suspended')this.ctx.resume();}catch(e){}},
    setMute(m){this.muted=m;if(this.master)this.master.gain.value=m?0:this.vol;},
    setVol(v){this.vol=v;if(this.master&&!this.muted)this.master.gain.value=v;},
    tone(freq,dur,type,vol,slideTo,when){if(!this.ctx||this.muted)return;const t=when||this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type||'square';o.frequency.setValueAtTime(freq,t);if(slideTo)o.frequency.exponentialRampToValueAtTime(Math.max(1,slideTo),t+dur);g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(vol||0.2,t+0.006);g.gain.exponentialRampToValueAtTime(0.0001,t+dur);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+dur+0.03);},
    noise(dur,vol,filt){if(!this.ctx||this.muted)return;const t=this.ctx.currentTime,n=this.ctx.createBufferSource(),buf=this.ctx.createBuffer(1,Math.max(1,this.ctx.sampleRate*dur),this.ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;n.buffer=buf;const g=this.ctx.createGain();g.gain.setValueAtTime(vol||0.2,t);g.gain.exponentialRampToValueAtTime(0.0001,t+dur);if(filt){const bp=this.ctx.createBiquadFilter();bp.type='bandpass';bp.frequency.value=filt;n.connect(bp);bp.connect(g);}else n.connect(g);g.connect(this.master);n.start(t);n.stop(t+dur+0.03);},
    shoot(){const n=performance.now();if(n-this.lastShot<34)return;this.lastShot=n;this.tone(700,0.05,'square',0.08,380);},
    kill(){this.tone(220,0.06,'sawtooth',0.07,130);this.noise(0.04,0.05,2200);},
    hurt(){this.tone(170,0.18,'sawtooth',0.2,70);this.noise(0.12,0.12,500);},
    over(){this.tone(150,0.3,'square',0.18,320);this.noise(0.3,0.13,800);},
    explo(){const n=performance.now();if(n-this.lastExplo<70)return;this.lastExplo=n;this.noise(0.25,0.26,300);this.tone(90,0.25,'sine',0.18,40);},
    cog(){const n=performance.now();if(n-this.lastCog<55)return;this.lastCog=n;this.tone(900,0.05,'triangle',0.04,1300);},
    relic(){if(!this.ctx)return;const c=this.ctx.currentTime;this.tone(520,0.12,'triangle',0.15,780,c);this.tone(780,0.18,'triangle',0.11,1040,c+0.07);},
    dash(){this.noise(0.12,0.13,1300);this.tone(440,0.12,'sine',0.09,920);},
    bomb(){this.noise(0.45,0.32,200);this.tone(65,0.45,'sine',0.26,28);},
    boss(){if(!this.ctx)return;const c=this.ctx.currentTime;this.tone(65,0.7,'sawtooth',0.24,110,c);this.tone(110,0.7,'square',0.12,55,c);},
    win(){if(!this.ctx||this.muted)return;const c=this.ctx.currentTime;[523,659,784,1047].forEach((f,i)=>this.tone(f,0.26,'triangle',0.18,null,c+i*0.13));},
    dead(){if(!this.ctx||this.muted)return;const c=this.ctx.currentTime;[300,220,150,90].forEach((f,i)=>this.tone(f,0.3,'sawtooth',0.2,null,c+i*0.13));},
    click(){this.tone(880,0.04,'square',0.06,1100);},
  };
