"use strict";
  const CH_BASE={vit:0,pow:0,ign:0,cool:0,coll:0,reroll:0,phoenix:0,pierceM:0,bspeed:0,critM:0,heatcap:0,magnetM:0,auftakt:0,dash:0,tank:0,pets:{},skin:'messing',lastPress:0};
  const UPGRADES=[
    {icon:'🔥',name:'Schnellfeuer',desc:'+15% Feuerrate',apply:p=>p.fireRate=Math.max(70,p.fireRate*0.85)},
    {icon:'⚔',name:'Schwere Munition',desc:'+6 Schaden',apply:p=>p.damage+=6},
    {icon:'➹',name:'Durchschlag',desc:'Schüsse durchdringen +1 Gegner',apply:p=>p.pierce+=1},
    {icon:'⫶',name:'Mehrlauf',desc:'+1 Projektil (Streuung)',apply:p=>{p.projectiles+=1;p.spread=0.16*(p.projectiles-1);}},
    {icon:'⇶',name:'Hochdruck',desc:'+22% Projektiltempo',apply:p=>p.bulletSpeed*=1.22},
    {icon:'⚙',name:'Laufwerk',desc:'+12% Tempo',apply:p=>p.speed*=1.12},
    {icon:'🛡',name:'Panzerung',desc:'+25 max. Dampf, voll auffüllen',apply:p=>{p.maxHp+=25;p.hp=p.maxHp;}},
    {icon:'❄',name:'Kühlrippen',desc:'+25% Kühlung, +15 Hitzelimit',apply:p=>{p.coolRate*=1.25;p.maxHeat+=15;}},
    {icon:'🛢',name:'Ölung',desc:'Heilt 35 Dampf je Raum',apply:p=>p.healPerRoom+=35},
    {icon:'💥',name:'Splittermunition',desc:'+30% Schaden, +12% Hitze/Schuss',apply:p=>{p.damage*=1.3;p.heatPerShot*=1.12;}},
    {icon:'🎯',name:'Zielspule',desc:'+8% Kritchance',apply:p=>p.crit+=0.08},
    {icon:'🩹',name:'Notdichtung',desc:'Heilt sofort 45 Dampf',apply:p=>p.hp=Math.min(p.maxHp,p.hp+45)},
    {icon:'🧨',name:'Druckausgleich',desc:'+18% Bomben-Aufladung',apply:p=>p.chargeRate*=1.18},
    {icon:'🔗',name:'Sammelmagnet',desc:'+45 Sammelreichweite',apply:p=>p.magnet+=45},
    {icon:'🌡',name:'Wärmetauscher',desc:'+20 Hitzelimit, +15% Kühlung',apply:p=>{p.maxHeat+=20;p.coolRate*=1.15;}},
  ];
  const METADEFS=[
    {id:'vit',icon:'🫧',name:'Verstärkter Kessel',desc:'+20 max. Dampf',max:6,cost:l=>60+l*55},
    {id:'pow',icon:'⚙',name:'Gehärtete Kolben',desc:'+4 Startschaden',max:6,cost:l=>75+l*65},
    {id:'ign',icon:'🔥',name:'Schnellzündung',desc:'-18ms Feuerrate',max:5,cost:l=>90+l*70},
    {id:'cool',icon:'❄',name:'Kühlrippen',desc:'+12 Startkühlung',max:5,cost:l=>65+l*55},
    {id:'heatcap',icon:'🌡',name:'Größerer Kessel',desc:'+12 Hitzelimit',max:4,cost:l=>65+l*55},
    {id:'pierceM',icon:'➹',name:'Bohrspitzen',desc:'+1 Start-Durchschlag',max:2,cost:l=>180+l*150},
    {id:'bspeed',icon:'⇶',name:'Druckkammer',desc:'+Startprojektiltempo',max:3,cost:l=>60+l*55},
    {id:'critM',icon:'🎯',name:'Feinmechanik',desc:'+5% Startkrit',max:4,cost:l=>110+l*85},
    {id:'dash',icon:'⤵',name:'Ausweichwerk',desc:'-15% Ausweich-Abklingzeit',max:3,cost:l=>110+l*90},
    {id:'tank',icon:'🧨',name:'Drucktank',desc:'+15% Bomben-Aufladung, +20% Bombenschaden',max:4,cost:l=>110+l*90},
    {id:'coll',icon:'🧲',name:'Magnetspule',desc:'+25% Zahnräder',max:4,cost:l=>90+l*80},
    {id:'magnetM',icon:'🔗',name:'Spulenkern',desc:'+25 Sammelreichweite',max:3,cost:l=>60+l*55},
    {id:'reroll',icon:'🎲',name:'Würfelwerk',desc:'+1 Neuwurf je Lauf',max:3,cost:l=>130+l*110},
    {id:'auftakt',icon:'🎁',name:'Auftakt',desc:'Start mit zufälligem Relikt',max:1,cost:l=>420},
    {id:'phoenix',icon:'⬆',name:'Notfall-Aufzug',desc:'+1 Wiederbelebung/Lauf',max:2,cost:l=>320+l*260},
  ];
  const PETS=[
    {id:'falke',icon:'🕊',name:'Kupfer-Falke',desc:'Umkreist dich und feuert automatisch auf nahe Gegner',cost:1100},
    {id:'hund',icon:'🐾',name:'Zahnrad-Hund',desc:'Folgt dir, beißt nahe Gegner und zieht Zahnräder an',cost:1000},
  ];
  const COSMETICS=[
    {id:'messing',name:'Messing',desc:'Der klassische Automat',cost:0,body:'#c89b5a',stroke:'#6b4f2a',hole:'#2e2117'},
    {id:'kupfer',name:'Kupferrost',desc:'Warmer Kupferton',cost:240,body:'#b5651d',stroke:'#6b3a10',hole:'#2e1808'},
    {id:'patina',name:'Grünspan',desc:'Alt und edel patiniert',cost:280,body:'#5a9c7a',stroke:'#2f5a45',hole:'#163024'},
    {id:'obsidian',name:'Obsidian',desc:'Mattschwarzes Gehäuse',cost:320,body:'#3a3a44',stroke:'#15151c',hole:'#0c0c12'},
    {id:'gold',name:'Goldwerk',desc:'Pures Prunkstück',cost:420,body:'#e8c170',stroke:'#9c7637',hole:'#3a2a10'},
    {id:'aether',name:'Aetherglanz',desc:'Leuchtend wie der Kern',cost:560,body:'#56d8e0',stroke:'#1a6e74',hole:'#0c2f33'},
    {id:'rubin',name:'Rubinwerk',desc:'Tiefes Rot mit Glanz',cost:480,body:'#c0392b',stroke:'#6e1f17',hole:'#2a0c08'},
    {id:'platin',name:'Platinguss',desc:'Kühles Edelmetall',cost:640,body:'#cdd6dd',stroke:'#6a737a',hole:'#1a2024'},
  ];
  const RELICS=[
    {id:'ueberdruck',icon:'💨',name:'Überdruckventil',desc:'Überhitzen löst eine Schockwelle aus'},
    {id:'kuehlkreis',icon:'❄',name:'Kühlkreislauf',desc:'Jeder Abschuss senkt die Hitze'},
    {id:'schrapnell',icon:'✺',name:'Schrapnellkern',desc:'Tote Gegner zerbersten in Splitter'},
    {id:'aether',icon:'⚡',name:'Aether-Leiter',desc:'Treffer springen auf nahe Gegner über'},
    {id:'schwungrad',icon:'🌀',name:'Schwungrad',desc:'Dauerfeuer steigert den Schaden (bis +60%)'},
    {id:'brennkammer',icon:'🔥',name:'Brennkammer',desc:'Treffer entzünden Gegner (Schaden über Zeit)'},
    {id:'dornen',icon:'🛡',name:'Dornenpanzer',desc:'Berührungsschaden wird reflektiert'},
    {id:'herz',icon:'❤',name:'Uhrwerkherz',desc:'Heilt periodisch etwas Dampf'},
    {id:'zwilling',icon:'⇄',name:'Zwillingslauf',desc:'Zusätzlicher Schuss nach hinten',onGain:p=>p.twin=true},
    {id:'magnetkern',icon:'🧲',name:'Magnetkern',desc:'Größere Reichweite; Zahnräder heilen',onGain:p=>{p.magnet=Math.max(p.magnet,210);p.cogHeal=true;}},
    {id:'praezision',icon:'🎯',name:'Präzisionsfokus',desc:'Keine Streuung, +25% Kritchance',onGain:p=>{p.noSpread=true;p.crit+=0.25;}},
    {id:'frost',icon:'❄️',name:'Frostkern',desc:'Treffer verlangsamen Gegner'},
    {id:'vampir',icon:'🩸',name:'Vampirzahnrad',desc:'Jeder Kill heilt 3 Dampf'},
    {id:'homing',icon:'🧭',name:'Schwerkraftspule',desc:'Schüsse lenken leicht auf Gegner zu',onGain:p=>p.homing=true},
    {id:'resonanz',icon:'💠',name:'Resonanzkern',desc:'Jeder 6. Schuss ist ein durchschlagender Großschuss'},
    {id:'explosiv',icon:'💣',name:'Sprengbolzen',desc:'Getötete Gegner explodieren'},
    {id:'schild',icon:'🔰',name:'Schildgenerator',desc:'Alle 10s ein Schutzschild (negiert 1 Treffer)'},
    {id:'quecksilber',icon:'💧',name:'Quecksilber',desc:'+18% Tempo, längere Unverwundbarkeit',onGain:p=>{p.speed*=1.18;p.iframeBonus=0.35;}},
    {id:'gluecksrad',icon:'🍀',name:'Glücksrad',desc:'+25% Zahnräder, +10% Krit',onGain:p=>{p.cogMult+=0.25;p.crit+=0.10;}},
    {id:'oelspur',icon:'🛢️',name:'Ölspur',desc:'Ausweichen hinterlässt eine schädigende Ölspur',onGain:p=>p.oiltrail=true},
    {id:'schwerlast',icon:'🏋',name:'Schwerlast',desc:'+45 max. Dampf, voll auffüllen',onGain:p=>{p.maxHp+=45;p.hp=p.maxHp;}},
    {id:'feinguss',icon:'🔩',name:'Feinguss',desc:'+1 Projektil & +1 Durchschlag',onGain:p=>{p.projectiles+=1;p.spread=0.16*(p.projectiles-1);p.pierce+=1;}},
    {id:'brennstoff',icon:'⛽',name:'Brennstoffzelle',desc:'+30% Schaden, +20% Hitze/Schuss',onGain:p=>{p.damage*=1.3;p.heatPerShot*=1.2;}},
    {id:'turbine',icon:'🌬',name:'Turbine',desc:'+20% Feuerrate & +12% Tempo',onGain:p=>{p.fireRate=Math.max(60,p.fireRate*0.8);p.speed*=1.12;}},
  ];
  const SYNERGIES=[
    {id:'dampfmaschine',name:'Dampfmaschine',req:['ueberdruck','kuehlkreis'],desc:'Schockwelle heilt pro Treffer'},
    {id:'streufeuer',name:'Streufeuer',req:['schrapnell','brennkammer'],desc:'Splitter entzünden ebenfalls'},
    {id:'kettenbrand',name:'Kettenbrand',req:['aether','brennkammer'],desc:'Kettenziele entzünden sich'},
    {id:'perpetuum',name:'Perpetuum',req:['schwungrad','kuehlkreis'],desc:'Schwungrad verfällt nicht bei Überhitzung'},
    {id:'igelpresse',name:'Igelpresse',req:['dornen','ueberdruck'],desc:'Reflexion löst Mini-Schockwelle aus'},
    {id:'splitterfrost',name:'Splitterfrost',req:['frost','explosiv'],desc:'Explosionen verlangsamen'},
    {id:'blutdruck',name:'Blutdruck',req:['vampir','ueberdruck'],desc:'Schockwelle heilt doppelt'},
    {id:'zielsuche',name:'Zielsuchsalve',req:['homing','resonanz'],desc:'Großschuss lenkt stark'},
    {id:'brandsatz',name:'Brandsatz',req:['explosiv','brennkammer'],desc:'Explosionen entzünden'},
    {id:'stachelschild',name:'Stachelschild',req:['schild','dornen'],desc:'Geblockter Treffer löst Schockwelle aus'},
    {id:'brandspur',name:'Brandspur',req:['oelspur','brennkammer'],desc:'Die Ölspur entzündet Gegner'},
    {id:'frostspur',name:'Frostspur',req:['oelspur','frost'],desc:'Die Ölspur verlangsamt Gegner stark'},
  ];
  const TYPES={
    crawler:{r:13,hp:20,speed:1.8,contact:12,drop:[1,2]},
    swarmling:{r:9,hp:9,speed:2.5,contact:8,drop:[1,1]},
    spitter:{r:14,hp:16,speed:1.0,contact:8,range:210,fireEvery:1300,drop:[2,3]},
    charger:{r:16,hp:34,speed:1.0,contact:20,drop:[2,4]},
    bomber:{r:15,hp:24,speed:2.0,contact:16,drop:[2,3]},
    brute:{r:23,hp:80,speed:0.7,contact:26,drop:[4,6]},
    turret:{r:16,hp:32,speed:0,range:9999,fireEvery:1000,drop:[3,4]},
    drohne:{r:11,hp:14,speed:2.2,contact:14,drop:[2,3],fly:true},
    waechter:{r:18,hp:55,speed:1.05,contact:16,drop:[3,5]},
    mechaniker:{r:14,hp:32,speed:1.2,contact:8,range:190,drop:[3,5]},
    moerser:{r:16,hp:30,speed:0.55,contact:12,range:280,drop:[3,4]},
    verstaerker:{r:15,hp:36,speed:1.1,contact:8,range:200,drop:[3,5]},
    juggernaut:{r:28,hp:140,speed:0.5,contact:34,drop:[6,9]},
    phantom:{r:11,hp:18,speed:2.8,contact:14,drop:[3,4],fly:true},
    geargrub:{r:8,hp:7,speed:2.2,contact:6,drop:[3,4]},
  };
  const ENEMYDEX=[
    {icon:'⚙',name:'Krabbler',desc:'Stürmt direkt auf dich zu. Einzeln harmlos, in Masse tödlich.'},
    {icon:'·',name:'Schwärmer',desc:'Winzig und sehr schnell, taucht in Gruppen auf. Wenig Leben.'},
    {icon:'◎',name:'Spucker',desc:'Hält Distanz, feuert gezielte Bolzen — nur bei freier Sicht.'},
    {icon:'▬',name:'Stürmer',desc:'Lädt auf und prescht vor; zielt auf deine erwartete Position.'},
    {icon:'✸',name:'Sprengkäfer',desc:'Rennt heran, zerbirst beim Tod in einen Geschossring. Auf Distanz töten.'},
    {icon:'⬣',name:'Panzergänger',desc:'Träge, sehr zäh, hoher Berührungsschaden. Kiten und zermürben.'},
    {icon:'⬡',name:'Geschützturm',desc:'Stationär, feuert dauerhaft gezielt bei Sichtlinie. Deckung nutzen.'},
    {icon:'✺',name:'Drohne',desc:'Fliegt über Wände, schnell, niedrig Leben. Keine Deckung sicher.'},
    {icon:'◗',name:'Wächter',desc:'Frontschild blockt Schüsse von vorn. Umkreisen und flankieren.'},
    {icon:'✚',name:'Mechaniker',desc:'Heilt nahe Gegner. Prioritätsziel — zuerst ausschalten.'},
    {icon:'◔',name:'Mörser',desc:'Wirft verzögerte Flächentreffer auf deine erwartete Position. In Bewegung bleiben.'},
    {icon:'◈',name:'Verstärker',desc:'Heizt nahe Gegner an: kurzzeitig schneller und sofort schussbereit. Vor den Verbündeten ausschalten.'},
    {icon:'★',name:'Elite (Gepanzert)',desc:'Goldene Aura: viel Leben, nimmt weniger Schaden. Doppelte Beute.'},
    {icon:'★',name:'Elite (Rasend)',desc:'Rote Aura: deutlich schneller und feuert öfter.'},
    {icon:'★',name:'Elite (Explosiv)',desc:'Orange Aura: zerbirst beim Tod in einen Geschossring.'},
  ];
  const BOSSDEX=[
    {icon:'⛁',name:'Der Kessel',desc:'Fächersalven & Radialbursts, ruft Adds herbei.'},
    {icon:'✳',name:'Die Spindel',desc:'Schnell, rotierende Geschossspiralen, stürmt heran.'},
    {icon:'🏭',name:'Die Fabrik',desc:'Beschwört Adds unter unverwundbarem Schild.'},
    {icon:'🕛',name:'Der Uhrturm',desc:'Sweepende Zeiger-Geschosse & Ringbursts.'},
    {icon:'⬢',name:'Der Koloss',desc:'Bodenstampfer mit dichten doppelten Geschosswellen.'},
    {icon:'❋',name:'Der Schwarm',desc:'Umkreisende Zahnräder, spuckt laufend Schwärmer.'},
    {icon:'🔥',name:'Der Brenner',desc:'Sweepender Flammenkegel & Ringbursts.'},
    {icon:'✂',name:'Der Zerleger',desc:'Prescht heran, zerlegt sich in Schwärmer, feuert Kreuz-Radialbursts.'},
    {icon:'❤',name:'Das Herzwerk',desc:'Endboss, dreiphasig: Fächer → Spiralen+Adds → Enrage.'},
  ];
  const ACHIEVEMENTS=[
    {name:'Erstes Blut',desc:'50 Gegner zerlegt',check:s=>s.kills>=50},
    {name:'Schlächter',desc:'1.000 Gegner zerlegt',check:s=>s.kills>=1000},
    {name:'Aufseher',desc:'Ersten Boss besiegt',check:s=>s.bosses>=1},
    {name:'Endzeit',desc:'Das Herzwerk besiegt',check:s=>s.endboss>=1},
    {name:'Tiefenläufer',desc:'Raum 15 erreicht',check:s=>s.bestRoom>=15},
    {name:'Maschinist',desc:'Raum 25 erreicht',check:s=>s.bestRoom>=25},
    {name:'Unter Druck',desc:'Lauf mit Druck ≥ 3',check:s=>s.bestPress>=3},
    {name:'Hochdruck',desc:'Lauf mit Druck ≥ 6',check:s=>s.bestPress>=6},
    {name:'Sammler',desc:'5.000 Zahnräder gesamt',check:s=>s.cogsTotal>=5000},
    {name:'Hartnäckig',desc:'25 Läufe gespielt',check:s=>s.runs>=25},
    {name:'Tiefseetaucher',desc:'Raum 40 erreicht',check:s=>s.bestRoom>=40},
    {name:'Großmeister',desc:'Lauf mit Druck ≥ 8',check:s=>s.bestPress>=8},
    {name:'Legende',desc:'5 Bosse besiegt',check:s=>s.bosses>=5},
    {name:'Schrottimperium',desc:'25.000 Zahnräder gesamt',check:s=>s.cogsTotal>=25000},
  ];
  const BIOMES=[
    {name:'Kesselhaus',floor:'#1c140d',wall:'#3a2a1a',wtop:'rgba(200,155,90,.18)',bg1:'#241a12',bg2:'#0b0805',ventMul:1,hazardType:null,fx:'kessel',fxDesc:'Bombe lädt schneller'},
    {name:'Frostspeicher',floor:'#101820',wall:'#243846',wtop:'rgba(150,200,230,.18)',bg1:'#16232e',bg2:'#070b0f',ventMul:0.6,hazardType:null,fx:'frost',fxDesc:'Waffe kühlt schneller'},
    {name:'Schmelzkammer',floor:'#1e1008',wall:'#4a2410',wtop:'rgba(255,150,80,.2)',bg1:'#2a1408',bg2:'#0d0603',ventMul:1.7,hazardType:'lava',fx:'lava',fxDesc:'Lava-Pfützen'},
    {name:'Aetherwerk',floor:'#141022',wall:'#2e2848',wtop:'rgba(150,160,255,.18)',bg1:'#1c1838',bg2:'#080612',ventMul:1,hazardType:null,fx:'aether',fxDesc:'Feindgeschosse werden gebremst'},
    {name:'Rostkatakomben',floor:'#161a12',wall:'#33401f',wtop:'rgba(170,200,120,.16)',bg1:'#1c2416',bg2:'#080a05',ventMul:0.8,hazardType:null,fx:'rost',fxDesc:'Gegner korrodieren langsam'},
    {name:'Dampfwerk',floor:'#16140f',wall:'#2e2a20',wtop:'rgba(210,200,170,.16)',bg1:'#22201a',bg2:'#0a0907',ventMul:1.4,hazardType:null,fx:'dampf',fxDesc:'Dampfstöße schleudern Gegner weg'},
    {name:'Hochofen',floor:'#1c0e06',wall:'#52260e',wtop:'rgba(255,170,90,.22)',bg1:'#2e1408',bg2:'#0e0502',ventMul:1.8,hazardType:null,fx:'glut',fxDesc:'Häufige Glut-Eruptionen'},
    {name:'Kristallhöhle',floor:'#181222',wall:'#33285a',wtop:'rgba(180,150,255,.2)',bg1:'#221a3a',bg2:'#0a0714',ventMul:0.7,hazardType:null,fx:'kristall',fxDesc:'Heilkristalle erscheinen'},
    {name:'Säurebad',floor:'#121a10',wall:'#2a3a18',wtop:'rgba(150,210,90,.18)',bg1:'#1a2612',bg2:'#070d05',ventMul:1.1,hazardType:null,fx:'saeure',fxDesc:'Säure zersetzt Gegner'},
    {name:'Tiefsee-Maschine',floor:'#0e1820',wall:'#1f3a4a',wtop:'rgba(120,200,230,.18)',bg1:'#142632',bg2:'#05101a',ventMul:0.5,hazardType:null,fx:'tiefsee',fxDesc:'Strömung zieht Zahnräder an'},
  ];
  const BOSSCFG={kessel:{name:'Der Kessel',r:48,hpMul:1.2,speed:0.5},spindel:{name:'Die Spindel',r:38,hpMul:1.0,speed:1.0},fabrik:{name:'Die Fabrik',r:52,hpMul:1.4,speed:0.35},uhrturm:{name:'Der Uhrturm',r:44,hpMul:1.2,speed:0.45},koloss:{name:'Der Koloss',r:62,hpMul:1.9,speed:0.3},schwarm:{name:'Der Schwarm',r:40,hpMul:1.0,speed:0.7},brenner:{name:'Der Brenner',r:46,hpMul:1.25,speed:0.5},zerleger:{name:'Der Zerleger',r:42,hpMul:1.3,speed:0.85},herzwerk:{name:'Das Herzwerk',r:60,hpMul:2.8,speed:0.5}};
